[book]
title = "Chant"
description = "Idempotent Intention"
authors = ["Chant Contributors"]
language = "en"
src = "."

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/lex00/chant"
edit-url-template = "https://github.com/lex00/chant/edit/main/docs/{path}"
site-url = "/docs/"
cname = "chant.dev"
additional-css = ["theme/custom.css"]
no-section-label = false

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
